/*
 * Module: Ultrasonic Driver
 *
 * File Name: UltraSonic.c
 *
 *
 * Author: Eman Sayed Hamdy
 */
#include"UltraSonic.h"
#include"icu.h"
#include"gpio.h"
#include"std_types.h"
#include<util/delay.h>
/*********************Global Variables*********************/
static uint8 g_edgeCount = 0;
uint16 distance ;
static uint16 g_timeHigh = 0;
static ICU_ConfigType ICU_Configurations = {F_CPU_8,RAISING};

/*********************Functions Definitions*********************/

/* Ultrasonic_init();
* Description:
▪ Initialize the ICU driver as required.
▪ Set up the ICU callback function.
▪ Set the direction for the trigger pin as output through
the GPIO driver.
*/
void Ultrasonic_init(void){
	ICU_init(&ICU_Configurations);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(TRIGGER_PORT_ID , TRIGGER_PIN_ID , PIN_OUTPUT);

}

/*Ultrasonic_Trigger();
 * Description:
▪ Send the trigger pulse to the ultrasonic sensor.*/
void Ultrasonic_Trigger(void){
	GPIO_writePin(TRIGGER_PORT_ID , TRIGGER_PIN_ID , LOGIC_HIGH);
	_delay_ms(10);
	GPIO_writePin(TRIGGER_PORT_ID , TRIGGER_PIN_ID , LOGIC_LOW);
}

/*Ultrasonic_readDistance();
 *  Send the trigger pulse by using the Ultrasonic_Trigger Function
 * Start the measurement process via the ICU driver.
 * */
uint16 Ultrasonic_readDistance(void){
	Ultrasonic_Trigger();
	if(g_edgeCount == 2)
	{
		g_edgeCount = 0 ;
		/* calculate the distance */
		float value = ((1.0 / (F_CPU / 8)) * 17000);
		 distance = (uint16)((g_timeHigh * value) + 1);
	}

	return distance ;
}

/*Ultrasonic_edgeProcessing
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 * */
void Ultrasonic_edgeProcessing(void){
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);
	}
}
